#!/bin/sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Get Nginx Version.
#======================================================================================================================

cd /tmp

VERSION=$(cat VERSION)
bcg-debug "Nginx version ${VERSION}."


#======================================================================================================================
# Install Nginx WebDAV extension and dependencies.
#======================================================================================================================

bcg-echo "Installing Nginx v${VERSION} WebDAV extension..."
apk add --no-cache \
    nginx-mod-http-dav-ext=${VERSION}
bcg-done
