#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Get Nginx Version.
#======================================================================================================================

cd /tmp

VERSION=$(cat NGINX_BUILD)
bf-echo "Nginx version ${VERSION}."


#======================================================================================================================
# Install Nginx WebDAV extension and dependencies.
#======================================================================================================================

bf-echo "Installing Nginx v${VERSION} WebDAV extension..."
apk add --no-cache \
    nginx-mod-http-dav-ext=${VERSION}
bf-done
