#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate configuration file.
#======================================================================================================================

bf-echo "Generating Nginx configuration file."
bf-esh ${BF_TEMPLATES}/localhost.conf.esh ${NGINX_LOCALHOST_CONF}
