#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Config is re-written every time in case environment variables have been changed
#======================================================================================================================

_echo "Writing Nginx WebDAV config..."
gomplate \
    -o /etc/nginx/sites/localhos.conf \
    -f /etc/templates/localhost.conf.tmpl
_done
