#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Config is re-written every time in case environment variables have been changed
#======================================================================================================================

bcg-echo "Writing Nginx WebDAV config..."
esh -o /etc/nginx/sites/localhost.conf \
    /etc/templates/localhost.conf.esh
bcg-done
