#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate configuration file.
#======================================================================================================================

bf-echo "Generating Nginx configuration file..."

esh -o ${NGINX_LOCALHOST_CONF} \
    ${BF_TEMPLATES}/localhost.conf.esh

bf-done
