#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Config is re-written every time in case environment variables have been changed.
#======================================================================================================================

bf-echo "Writing Nginx WebDAV config..."
esh -o ${NGINX_LOCALHOST_CONF} \
    ${BCG_TEMPLATES}/localhost.conf.esh
bf-done
