name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION_MAJOR
        id: version_major
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/nginx-webdav:latest
            bfren/nginx-webdav:${{ steps.version_major.outputs.contents }}
            bfren/nginx-webdav:${{ steps.version_minor.outputs.contents }}
            bfren/nginx-webdav:${{ steps.version.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
